version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: music-collab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: music_collab_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - music-collab-network

  redis:
    image: redis:7-alpine
    container_name: music-collab-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass dev_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - music-collab-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: music-collab-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@musiccollab.local
      PGADMIN_DEFAULT_PASSWORD: admin_password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - music-collab-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: music-collab-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:dev_redis_password
      HTTP_USER: admin
      HTTP_PASSWORD: admin_password
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - music-collab-network

networks:
  music-collab-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
